### ISSUE TITLE
Translation for PT-BR

### ISSUE THREAD

**Issue by bkdwt** [namazso/WinDiskFlash#1]
Hey man, how is going? I don't know how to do things here on GitHub, so I did the translation in the notepad and I'm posting it here for you to add to the application.

```
STRINGTABLE
BEGIN
    IDS_DLG_0_LICENSE       "0. Licença"
    IDS_DLG_1_DEVICE        "1. Dispositivo"
    IDS_DLG_2_OPERATION     "2. Operação"
    IDS_DLG_3_FILE          "3. Arquivo"
    IDS_DLG_4_FLASH         "4. Gravar"
    IDS_DLG_LICENSE_BTN     "Ler os termos"
    IDS_DLG_LICENSE_CHECK   "Eu concordo com os termos"
    IDS_DLG_WARRANTY_CHECK  "Entendo que este programa é fornecido com absolutamente NENHUMA GARANTIA DE QUALQUER TIPO."
    IDS_DLG_REFRESH         "Atualizar"
    IDS_DLG_OPERATION_RAW   "Gravar nova imagem no disco"
    IDS_DLG_OPERATION_TRASH "Excluir tabelas de partição"
    IDS_DLG_BROWSE          "Procurar..."
    IDS_CLOSE               "Fechar"
    IDS_DLG_OPERATION_SAVE  "Salvar uma imagem do disco"
END
```

Be safe! :)

**Comment by namazso** [comment]
All good, thanks.
Could you translate the other stringtable too? Seems like VS split it in two sometime:
```txt
STRINGTABLE
BEGIN
    IDS_APP_TITLE           "WinDiskFlash"
    IDS_WRITE_MORE_THAN_DISK 
                            "Disk is {0} bytes, but you asked to write {1} bytes, which is more. Continue?"
    IDS_CANNOT_QUIT_WHILE_RUNNING "Cannot quit while flashing is in progress."
    IDS_DLG_START           "Start"
    IDS_CANCEL              "Cancel"
    IDS_ERROR               "Error"
    IDC_WINDISKFLASH        "WINDISKFLASH"
    IDS_WARNING             "Warning"
    IDS_SUCCESS             "Success"
END
```
I'll probably incorporate https://github.com/namazso/langcomp for slightly less bad translation management later

**Comment by bkdwt** [comment]
> All good, thanks.
> Could you translate the other stringtable too? Seems like VS split it in two sometime:
> 
> ```
> STRINGTABLE
> BEGIN
>     IDS_APP_TITLE           "WinDiskFlash"
>     IDS_WRITE_MORE_THAN_DISK 
>                             "Disk is {0} bytes, but you asked to write {1} bytes, which is more. Continue?"
>     IDS_CANNOT_QUIT_WHILE_RUNNING "Cannot quit while flashing is in progress."
>     IDS_DLG_START           "Start"
>     IDS_CANCEL              "Cancel"
>     IDS_ERROR               "Error"
>     IDC_WINDISKFLASH        "WINDISKFLASH"
>     IDS_WARNING             "Warning"
>     IDS_SUCCESS             "Success"
> END
> ```
> 
> I'll probably incorporate https://github.com/namazso/langcomp for slightly less bad translation management later

Here we go: 

```
STRINGTABLE
BEGIN
    IDS_APP_TITLE           "WinDiskFlash"
    IDS_WRITE_MORE_THAN_DISK 
                            "O disco tem {0} bytes, mas você pediu para escrever {1} bytes, o que é mais. Continuar?"
    IDS_CANNOT_QUIT_WHILE_RUNNING "Não é possível fechar enquanto a gravação está em andamento."
    IDS_DLG_START           "Começar"
    IDS_CANCEL              "Cancelar"
    IDS_ERROR               "Erro"
    IDC_WINDISKFLASH        "WINDISKFLASH"
    IDS_WARNING             "Aviso"
    IDS_SUCCESS             "Sucesso"
END
```

;)
